import { DefaultTheme } from 'styled-components';
import {
	borderRadius,
	buttonBackgroundColor,
	buttonBorderRadius,
	distanceL,
	distanceM,
	distanceS,
	distanceXL,
	distanceXS,
	distanceXXL,
	doughnutColors,
	errorBackgroundColor,
	fontSizeL,
	fontSizeM,
	fontSizeS,
	fontSizeXL,
	fontSizeXS,
	fontSizeXXL,
	fontSizeXXS,
	fontWeightBold,
	fontWeightNormal,
	inputHeight,
	mobileThreshold,
	onErrorColor,
	onPrimaryBrandColor,
	onSecondaryBrandColor,
	opacityHeavy,
	opacityLight,
	opacityNormal,
	primaryBackgroundColor,
	primaryBrandColor,
	primaryColor,
	primaryErrorColor,
	quaternaryBackgroundColor,
	secondaryBackgroundColor,
	secondaryBrandColor,
	secondaryColor,
	shadowColor,
	tertiaryBackgroundColor,
	tertiaryColor,
	underPrimaryBandColor,
	greenyColor,
	lightBlackColor,
	purpleColor,
} from 'styles/base';

export const theme: DefaultTheme = {
	primaryColor,
	purpleColor,
	secondaryColor,
	lightBlackColor,
	tertiaryColor,
	greenyColor,
	primaryBrandColor,
	secondaryBrandColor,
	onPrimaryBrandColor,
	onSecondaryBrandColor,
	primaryBackgroundColor,
	secondaryBackgroundColor,
	tertiaryBackgroundColor,
	quaternaryBackgroundColor,
	buttonBackgroundColor,
	underPrimaryBandColor,
	primaryErrorColor,
	errorBackgroundColor,
	onErrorColor,
	doughnutColors,
	shadowColor,

	fontSizeXXS,
	fontSizeXS,
	fontSizeS,
	fontSizeM,
	fontSizeL,
	fontSizeXL,
	fontSizeXXL,

	fontWeightNormal,
	fontWeightBold,

	opacityLight,
	opacityNormal,
	opacityHeavy,

	inputHeight,
	borderRadius,
	buttonBorderRadius,
	distanceXS,
	distanceS,
	distanceM,
	distanceL,
	distanceXL,
	distanceXXL,

	mobileThreshold,
};
